apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: ""  # Use the default storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
