services:
  app:
    build: .
    image: node-app36:v1
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:

networks:
  app-network:

