auth_enabled: false # no auth (perfect for local/dev)

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1  # single-node setup (t2.micro friendly)
  path_prefix: /loki

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb # modern Loki storage engine
      object_store: filesystem  # logs stored locally (cheap + simple)
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
