[web]
web1 ansible_host=34.226.209.54

[app]
app1 ansible_host=107.21.44.255

[db]
db1 ansible_host=98.89.48.21

[application:children]
web
app

[all_servers:children]
application
db

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/ansible-key.pem
