[web]
34.228.66.209 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-key.pem

[app]
52.201.255.253 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-key.pem

[db]
54.172.101.45 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-key.pem
