user www-data;
worker_processes auto;
pid /run/nginx.pid;
events {
    worker_connections 768;
}
http {
    sendfile on;
    server {
        listen 80 default_server;
        root /usr/share/nginx/html;
        index index.html;
    }
}
